# Generated by Django 5.2.17 on 2026-09-28 04:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0002_submissiondeletiontombstone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyScreening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detector_version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('flags_found', 'Potential identifying details found'), ('no_automated_flags', 'No automated flags'), ('error', 'Screening error')], max_length=32)),
                ('finding_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_screenings', to='submissions.rawsubmission')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='privacy_review.privacyscreening')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('url', 'URL'), ('social_handle', 'Social handle'), ('precise_date', 'Precise date'), ('street_address', 'Street address'), ('explicit_name', 'Explicit name disclosure')], max_length=32)),
                ('rule_id', models.CharField(max_length=64)),
                ('start_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='privacy_review.privacyscreening')),
            ],
            options={
                'ordering': ['start_offset', 'end_offset'],
            },
        ),
        migrations.AddIndex(
            model_name='privacyscreening',
            index=models.Index(fields=['submission', '-created_at'], name='privacy_rev_submiss_bead29_idx'),
        ),
        migrations.AddIndex(
            model_name='privacyscreening',
            index=models.Index(fields=['status', 'created_at'], name='privacy_rev_status_1d7004_idx'),
        ),
        migrations.AddConstraint(
            model_name='privacyfinding',
            constraint=models.UniqueConstraint(fields=('screening', 'rule_id', 'start_offset', 'end_offset'), name='privacy_unique_finding_span'),
        ),
    ]
