# Generated by Django 5.2.17 on 2026-09-28 05:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0003_consent_supersedes_restrict'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('in_review', 'In review'), ('escalated', 'Escalated'), ('approved', 'Approved for later publication'), ('rejected', 'Rejected')], default='pending', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_moderation_cases', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_case', to='submissions.rawsubmission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('case_created', 'Case created'), ('claimed', 'Claimed'), ('draft_created', 'Redaction draft created'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], max_length=32)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('reason_code', models.CharField(blank=True, max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderation_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='moderation.moderationcase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedactionDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('redacted_text', models.TextField()),
                ('content_warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='moderation.moderationcase')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_drafts', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='superseded_by', to='moderation.redactiondraft')),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['status', 'created_at'], name='moderation__status_8eaa85_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['assigned_to', 'status'], name='moderation__assigne_78362b_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationevent',
            index=models.Index(fields=['case', 'created_at'], name='moderation__case_id_2ddcff_idx'),
        ),
        migrations.AddConstraint(
            model_name='redactiondraft',
            constraint=models.UniqueConstraint(fields=('case', 'version'), name='moderation_unique_draft_version'),
        ),
    ]
