SUBMISSION_SCHEMA_VERSION = "submission-schema-1"
PUBLICATION_CONSENT_VERSION = "consent-publication-2026.1"
STATISTICS_CONSENT_VERSION = "consent-statistics-2026.1"
PRIVACY_POLICY_VERSION = "privacy-policy-2026.1"
SOURCE_FLOW_VERSION = "web-2026.1"

MAX_STORY_LENGTH = 6000
MAX_PEOPLE_INVOLVED = 20
MAX_PERIODS = 20
MAX_EXPERIENCE_TYPES = 8
