# Generated by Django 5.2.17 on 2026-09-28 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=64)),
                ('age_group', models.CharField(max_length=24)),
                ('relationship', models.CharField(max_length=32)),
                ('setting', models.CharField(max_length=32)),
                ('experience_types', models.JSONField(default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('excerpt', models.CharField(max_length=320)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_story_id', models.UUIDField(unique=True)),
                ('source_case_id', models.UUIDField(unique=True)),
                ('source_draft_id', models.UUIDField()),
                ('source_draft_version', models.PositiveIntegerField()),
                ('approval_event_id', models.UUIDField()),
                ('control_mode', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderation_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_publication_records', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('received', 'Received')], default='received', editable=False, max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='public_stories.publicstory')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
