# Generated by Django 5.2.17 on 2026-09-28 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicRemovalCredential',
            fields=[
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='removal_credential', serialize=False, to='public_stories.publicstory')),
                ('verifier', models.CharField(max_length=256)),
                ('copied_at', models.DateTimeField(auto_now_add=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
