# Generated by Django 5.2.17 on 2026-09-28 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('received', 'Received')], default='received', editable=False, max_length=24)),
                ('age_group', models.CharField(max_length=24)),
                ('setting', models.CharField(max_length=32)),
                ('experience_types', models.JSONField(default=list)),
                ('people_involved', models.JSONField(blank=True, default=list)),
                ('frequency', models.CharField(blank=True, max_length=32)),
                ('periods', models.JSONField(blank=True, default=list)),
                ('story_text', models.TextField(blank=True)),
                ('publication_choice', models.CharField(choices=[('public', 'Public after moderation'), ('statistics_only', 'Statistics only')], max_length=24)),
                ('schema_version', models.CharField(default='submission-schema-1', editable=False, max_length=64)),
                ('privacy_policy_version', models.CharField(default='privacy-policy-2026.1', editable=False, max_length=64)),
                ('source_flow_version', models.CharField(default='web-2026.1', editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retention_expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemovalCredential',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='removal_credential', serialize=False, to='submissions.rawsubmission')),
                ('verifier', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('publication', 'Public story publication'), ('statistics', 'Aggregate statistics')], max_length=24)),
                ('granted', models.BooleanField()),
                ('consent_text_version', models.CharField(max_length=64)),
                ('privacy_policy_version', models.CharField(default='privacy-policy-2026.1', max_length=64)),
                ('schema_version', models.CharField(default='submission-schema-1', max_length=64)),
                ('source_flow_version', models.CharField(default='web-2026.1', max_length=64)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='submissions.consentrecord')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='submissions.rawsubmission')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
