# Generated by Django 5.2.17 on 2026-09-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionDeletionTombstone',
            fields=[
                ('submission_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('retention_expired', 'Retention expired')], max_length=32)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('retention_expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['deleted_at'],
            },
        ),
    ]
