# Generated by Django 5.2.17 on 2026-09-28 08:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsContribution",
            fields=[
                (
                    "source_submission_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("age_group", models.CharField(max_length=24)),
                ("setting", models.CharField(max_length=32)),
                ("experience_types", models.JSONField(default=list)),
                ("relationship_categories", models.JSONField(blank=True, default=list)),
                ("statistics_consent_record_id", models.UUIDField(editable=False)),
                ("consent_text_version", models.CharField(editable=False, max_length=64)),
                ("privacy_policy_version", models.CharField(editable=False, max_length=64)),
                ("schema_version", models.CharField(editable=False, max_length=64)),
                ("source_flow_version", models.CharField(editable=False, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("retention_expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("dataset_version", models.CharField(editable=False, max_length=96, unique=True)),
                ("privacy_policy_version", models.CharField(editable=False, max_length=64)),
                ("generated_label", models.CharField(editable=False, max_length=96)),
                (
                    "total_band",
                    models.CharField(blank=True, default="", editable=False, max_length=24),
                ),
                ("payload", models.JSONField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
